# Example 2
#
# Single box with VirtualBox provider.
#
# NOTE: Make sure you have the precise32 base box installed...
# vagrant box add precise32 http://files.vagrantup.com/precise32.box
#
# VirtualBox modifyvm docs: http://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "obc.devbox"
  config.vm.network "private_network", ip: "192.168.50.5"
  config.vm.provision "shell", path: "./configure.sh", privileged: true

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
    vb.name = "OBC DEV" 
    vb.cpus = 4
    vb.memory = 2048

    # Fixes slow bootup bug
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
end